#!/bin/sh
for app in system-of-record mint the-shed; do
	if [ -e $app ] ; then
		echo "getting latest: $app"
		cd $app
		git pull
		cd -
	else 
		echo "getting for first time: $app"
		git clone git@github.com:LandRegistry/$app.git
	fi
done

