#!/bin/sh
git clone git@github.com:LandRegistry/concept-geo-service.git
git clone git@github.com:LandRegistry/concept-homepage.git
git clone git@github.com:LandRegistry/concept-frontend.git
git clone git@github.com:LandRegistry/concept-performance-dashboard.git
git clone git@github.com:LandRegistry/concept-register-data.git
git clone git@github.com:LandRegistry/concept-system-of-record.git
git clone git@github.com:LandRegistry/concept-titles-service.git
git clone git@github.com:LandRegistry/concept-update-register.git
git clone git@github.com:LandRegistry/concept-thirdparty.git
git clone git@github.com:LandRegistry/concept-official-copy.git
git clone git@github.com:LandRegistry/system-of-record.git
git clone git@github.com:LandRegistry/mint.git
git clone git@github.com:helmi03/docker-postgis.git
