#!/bin/sh
git clone git@github.com:LandRegistry/concept-homepage.git
git clone git@github.com:LandRegistry/concept-my-property.git
git clone git@github.com:LandRegistry/concept-performance-dashboard.git
git clone git@github.com:LandRegistry/concept-system-of-record.git
git clone git@github.com:LandRegistry/concept-titles-service.git
git clone git@github.com:LandRegistry/concept-update-register.git

