#!/bin/bash
 
apps=(landregistry/concept-geo-service landregistry/concept-homepage landregistry/concept-frontend landregistry/concept-performance-dashboard landregistry/concept-register-data landregistry/concept-system-of-record landregistry/concept-titles-service landregistry/concept-update-register landregistry/concept-thirdparty landregistry/concept-official-copy landregistry/system-of-record landregistry/mint helmi03/docker-postgis  )

source script/_bstrap
bstrap "${apps[@]}"
